services:
  mongodb:
    image: mongo:latest
    container_name: weather_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=weather_user
      - MONGO_INITDB_ROOT_PASSWORD=weather_password
    networks:
      - weather_network

  weather_script:
    build:
      context: ./python-scripts
      dockerfile: Dockerfile
    container_name: weather_script
    depends_on:
      - mongodb
    volumes:
      - ./python-scripts:/app
    networks:
      - weather_network
    command: >
      bash -c "
        python get_data.py &&
        python stash_data.py
      "

  jupyter:
    build:
      context: ./python-scripts
      dockerfile: Dockerfile
    container_name: weather_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./python-scripts:/app
      - jupyter_data:/root/.local/share/jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - mongodb
    networks:
      - weather_network
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

volumes:
  mongodb_data:
  jupyter_data:

networks:
  weather_network:
    driver: bridge 